services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - database
    ports:
      - "8000:8000"
    working_dir: /var/www
    command: php -S 0.0.0.0:8000 -t public

  database:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kids-bulle
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:



